### ISSUE TITLE
JedisConnectionException: Could not get a resource from the pool

### ISSUE THREAD

**Issue by shannonantony** [RediSearch/JRediSearch#173]
Hi,

I am loading around 1million record into RediSearch. During the data load, I get following exception, 

redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.jedis.util.Pool.getResource(Pool.java:84)
        at redis.clients.jedis.JedisSentinelPool.getResource(JedisSentinelPool.java:310)
        at redis.clients.jedis.JedisSentinelPool.getResource(JedisSentinelPool.java:17)
        at io.redisearch.client.Client.connection(Client.java:144)
        at com.altice.searchcloud.service.MetaDataCacheLoadService.loadMetaDataRedis(MetaDataCacheLoadService.java:134)
        at com.altice.searchcloud.service.MetaDataCacheLoadService.loadChunk(MetaDataCacheLoadService.java:111)
        at com.altice.searchcloud.service.MetaDataCacheLoadService.lambda$loadEventMetadata$1(MetaDataCacheLoadService.java:101)
        at com.altice.searchcloud.service.DbLoadService$2.call(DbLoadService.java:67)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.

PLease let me know what should I do to resolve this issue

Appreciate your help

thanks

Jason

**Comment by sazzad16** [comment]
@shannonantony Please check (and focus) on `Failed to create socket`. There seems to be some issues when creating the connections. And given information is not enough even to guess.
