### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by zhangdongbj** [RediSearch/JRediSearch#42]
when loading client :Exception in thread "main" java.lang.UnsupportedClassVersionError: io/redisearch/client/Client : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.visionvera.ssm.util.redisearchTest.main(redisearchTest.java:24)

**Comment by gkorland** [comment]
@zhangdongbj which version are you using? on which JDK version are you running?
