### ISSUE TITLE
jedisPool Exception

### ISSUE THREAD

**Issue by David1013** [RediSearch/JRediSearch#58]
I created a connection:Client client = new Client(...);But watch the client,find jedisPool a Exeception:
java.lang.Exception
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.<init>(BaseGenericObjectPool.java:147)
	at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:105)
	at redis.clients.jedis.util.Pool.initPool(Pool.java:45)
	at redis.clients.jedis.util.Pool.<init>(Pool.java:24)
	at redis.clients.jedis.JedisPoolAbstract.<init>(JedisPoolAbstract.java:15)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:181)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:145)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:127)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:76)
	at io.redisearch.client.Client.<init>(Client.java:68)
is this version question, please?

**Comment by gkorland** [comment]
@David1013 thanks for opening the issue, can you please add a full test case?
